src/Bonsai/Areas/Admin/ViewModels/Relations/RelationEditorDataVM.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Strongly typed structure for additional properties of the Relation editor.
    /// </summary>
    public class RelationEditorDataVM
    {
        public bool IsNew { get; set; }

        public RelationEditorPropertiesVM Properties { get; set; }

        public IEnumerable<SelectListItem> SourceItems { get; set; }
        public IEnumerable<SelectListItem> DestinationItem { get; set; }
        public IEnumerable<SelectListItem> EventItem { get; set; }
        public IEnumerable<SelectListItem> RelationTypes { get; set; }
    }
}

src/Bonsai/Areas/Admin/ViewModels/Relations/RelationEditorPropertiesVM.cs
using System.Collections.Generic;
using Bonsai.Data.Models;

namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Extended properties for the relation editor.
    /// </summary>
    public class RelationEditorPropertiesVM
    {
        public string SourceName { get; set; }
        public string DestinationName { get; set; }

        public IReadOnlyList<PageType> SourceTypes { get; set; }
        public IReadOnlyList<PageType> DestinationTypes { get; set; }

        public bool ShowDuration { get; set; }
        public bool ShowEvent { get; set; }
    }
}

src/Bonsai/Areas/Admin/ViewModels/Relations/RelationEditorVM.cs
using System;
using AutoMapper;
using Bonsai.Areas.Admin.Logic.Changesets;
using Bonsai.Code.Infrastructure;
using Bonsai.Code.Utils.Date;
using Bonsai.Code.Utils.Helpers;
using Bonsai.Data.Models;

namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Editable details of a relation.
    /// </summary>
    public class RelationEditorVM: IMapped, IVersionable
    {
        /// <summary>
        /// Surrogate ID.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// ID of the source page.
        /// </summary>
        public Guid[] SourceIds { get; set; }

        /// <summary>
        /// ID of the second page.
        /// </summary>
        public Guid? DestinationId { get; set; }

        /// <summary>
        /// ID of the related event.
        /// </summary>
        public Guid? EventId { get; set; }

        /// <summary>
        /// Type of the relation.
        /// </summary>
        public RelationType Type { get; set; }

        /// <summary>
        /// Relation timespan's start.
        /// </summary>
        public string DurationStart { get; set; }

        /// <summary>
        /// Relation timespan's end.
        /// </summary>
        public string DurationEnd { get; set; }

        public void Configure(IProfileExpression profile)
        {
            profile.CreateMap<Relation, RelationEditorVM>()
                   .MapMember(x => x.Id, x => x.Id)
                   .MapMember(x => x.SourceIds, x => new [] { x.SourceId })
                   .MapMember(x => x.DestinationId, x => x.DestinationId)
                   .MapMember(x => x.EventId, x => x.EventId)
                   .MapMember(x => x.Type, x => x.Type)
                   .MapMember(x => x.DurationStart, x => FuzzyRange.TrySplit(x.Duration)[0])
                   .MapMember(x => x.DurationEnd, x => FuzzyRange.TrySplit(x.Duration)[1])
                   .ReverseMap()
                   .MapMember(x => x.Duration, x => FuzzyRange.TryCombine(x.DurationStart, x.DurationEnd))
                   .MapMember(x => x.SourceId, x => x.SourceIds != null && x.SourceIds.Length > 0 ? x.SourceIds[0] : Guid.Empty);
        }
    }
}

src/Bonsai/Areas/Admin/ViewModels/Relations/RelationSuggestQueryVM.cs
using System;
using Bonsai.Data.Models;

namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Collection of arguments for a page lookup in relation editor.
    /// </summary>
    public class RelationSuggestQueryVM
    {
        /// <summary>
        /// Search query.
        /// </summary>
        public string Query { get; set; }

        /// <summary>
        /// List of expected page types.
        /// </summary>
        public PageType[] Types { get; set; }

        /// <summary>
        /// Selected relation type.
        /// </summary>
        public RelationType RelationType { get; set; }

        /// <summary>
        /// Selected source page ID (for destination picking).
        /// </summary>
        public Guid? SourceId { get; set; }

        /// <summary>
        /// Selected destination page ID (for source picking).
        /// </summary>
        public Guid? DestinationId { get; set; }
    }
}

src/Bonsai/Areas/Admin/ViewModels/Relations/RelationTitleVM.cs
using System;
using AutoMapper;
using Bonsai.Areas.Front.ViewModels.Page;
using Bonsai.Code.Infrastructure;
using Bonsai.Code.Utils.Date;
using Bonsai.Code.Utils.Helpers;
using Bonsai.Data.Models;

namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Brief information about a relation between two pages.
    /// </summary>
    public class RelationTitleVM: IMapped
    {
        /// <summary>
        /// Surrogate ID.
        /// </summary>
        public Guid Id { get; set; }
        
        /// <summary>
        /// The first entity in the relation.
        /// </summary>
        public PageTitleExtendedVM Source { get; set; }

        /// <summary>
        /// The second entity in the relation.
        /// </summary>
        public PageTitleExtendedVM Destination { get; set; }

        /// <summary>
        /// Related event (e.g. wedding).
        /// </summary>
        public PageTitleExtendedVM Event { get; set; }

        /// <summary>
        /// Type of the relation.
        /// </summary>
        public RelationType Type { get; set; }

        /// <summary>
        /// Timespan of the relation.
        /// </summary>
        public FuzzyRange? Duration { get; set; }

        public void Configure(IProfileExpression profile)
        {
            profile.CreateMap<Relation, RelationTitleVM>()
                   .MapMember(x => x.Id, x => x.Id)
                   .MapMember(x => x.Type, x => x.Type)
                   .MapMemberDynamic(x => x.Source, x => x.Source)
                   .MapMemberDynamic(x => x.Destination, x => x.Destination)
                   .MapMemberDynamic(x => x.Event, x => x.Event)
                   .MapMember(x => x.Duration, x => FuzzyRange.TryParse(x.Duration));
        }
    }
}

src/Bonsai/Areas/Admin/ViewModels/Relations/RelationsListDataVM.cs
namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Additional data for relation filters.
    /// </summary>
    public class RelationsListDataVM
    {
        /// <summary>
        /// Title of the filtered entity.
        /// </summary>
        public string EntityTitle { get; set; }
    }
}

src/Bonsai/Areas/Admin/ViewModels/Relations/RelationsListRequestVM.cs
using System;
using Bonsai.Areas.Admin.ViewModels.Common;
using Bonsai.Data.Models;

namespace Bonsai.Areas.Admin.ViewModels.Relations
{
    /// <summary>
    /// Request for finding relations.
    /// </summary>
    public class RelationsListRequestVM: ListRequestVM
    {
        /// <summary>
        /// Filter by entity.
        /// </summary>
        public Guid? EntityId { get; set; }

        /// <summary>
        /// Allowed types of relations.
        /// </summary>
        public RelationType[] Types { get; set; }

        /// <summary>
        /// Checks if the request has no filter applied.
        /// </summary>
        public override bool IsEmpty()
        {
            return base.IsEmpty()
                   && EntityId == null
                   && (Types == null || Types.Length == 0);
        }
    }
}

src/Bonsai/Areas/Admin/Controllers/ChangesetsController.cs
using System;
using System.Threading.Tasks;
using Bonsai.Areas.Admin.Logic.Changesets;
using Bonsai.Areas.Admin.ViewModels.Changesets;
using Bonsai.Code.Utils;
using Bonsai.Data;
using Microsoft.AspNetCore.Mvc;

namespace Bonsai.Areas.Admin.Controllers
{
    /// <summary>
    /// Controller for managing changesets.
    /// </summary>
    [Route("admin/changes")]
    public class ChangesetsController: AdminControllerBase
    {
        public ChangesetsController(ChangesetsManagerService changes, AppDbContext db)
        {
            _changes = changes;
            _db = db;
        }

        private readonly ChangesetsManagerService _changes;
        private readonly AppDbContext _db;

        #region Public methods

        /// <summary>
        /// Displays the list of all changesets.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Index(ChangesetsListRequestVM request)
        {
            var vm = await _changes.GetChangesetsAsync(request);
            return View(vm);
        }

        /// <summary>
        /// Displays the information about a particular changeset.
        /// </summary>
        [HttpGet]
        [Route("details")]
        public async Task<ActionResult> Details(Guid id)
        {
            var vm = await _changes.GetChangesetDetailsAsync(id);
            return View(vm);
        }

        /// <summary>
        /// Displays the changeset revert confirmation.
        /// </summary>
        [HttpGet]
        [Route("revert")]
        public async Task<ActionResult> Revert(Guid id)
        {
            var vm = await _changes.GetChangesetDetailsAsync(id);
            if (!vm.CanRevert)
                throw new OperationException("Эта правка не может быть отменена");

            return View(vm);
        }

        /// <summary>
        /// Reverts the edit to its original state.
        /// </summary>
        [HttpPost]
        [Route("revert")]
        public async Task<ActionResult> Revert(Guid id, bool confirm)
        {
            var editVm = await _changes.GetChangesetDetailsAsync(id);
            if (!editVm.CanRevert)
                throw new OperationException("Эта правка не может быть отменена");

            await _changes.RevertChangeAsync(id, User);
            await _db.SaveChangesAsync();

            return RedirectToSuccess("Правка была отменена");
        }

        #endregion
    }
}

src/Bonsai/Areas/Admin/Controllers/RelationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bonsai.Areas.Admin.Logic;
using Bonsai.Areas.Admin.Logic.Workers;
using Bonsai.Areas.Admin.ViewModels.Relations;
using Bonsai.Code.Utils.Validation;
using Bonsai.Data;
using Bonsai.Data.Models;
using Impworks.Utils.Format;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Bonsai.Areas.Admin.Controllers
{
    /// <summary>
    /// Controller for managing relations.
    /// </summary>
    [Route("admin/relations")]
    public class RelationsController: AdminControllerBase
    {
        public RelationsController(RelationsManagerService rels, PagesManagerService pages, AppDbContext db, WorkerAlarmService alarm)
        {
            _rels = rels;
            _pages = pages;
            _db = db;
            _alarm = alarm;
        }

        private readonly RelationsManagerService _rels;
        private readonly PagesManagerService _pages;
        private readonly AppDbContext _db;
        private readonly WorkerAlarmService _alarm;

        /// <summary>
        /// Displays the list of relations.
        /// </summary>
        [HttpGet]
        [Route("")]
        public async Task<ActionResult> Index(RelationsListRequestVM request)
        {
            ViewBag.Data = await GetDataAsync(request);
            var rels = await _rels.GetRelationsAsync(request);
            return View(rels);
        }

        /// <summary>
        /// Dispays the editor form for a new relation.
        /// </summary>
        [HttpGet]
        [Route("create")]
        public async Task<ActionResult> Create()
        {
            return await ViewEditorFormAsync(new RelationEditorVM { Type = RelationType.Child });
        }

        /// <summary>
        /// Attempts to create a new page.
        /// </summary>
        [HttpPost]
        [Route("create")]
        public async Task<ActionResult> Create(RelationEditorVM vm)
        {
            if(!ModelState.IsValid)
                return await ViewEditorFormAsync(vm);

            try
            {
                await _rels.CreateAsync(vm, User);
                await _db.SaveChangesAsync();
                _alarm.FireTreeLayoutRegenerationRequired();

                return RedirectToSuccess("Связь создана");
            }
            catch(ValidationException ex)
            {
                SetModelState(ex);
                return await ViewEditorFormAsync(vm);
            }
        }

        /// <summary>
        /// Displays the editor for an existing relation.
        /// </summary>
        [HttpGet]
        [Route("update")]
        public async Task<ActionResult> Update(Guid id)
        {
            var vm = await _rels.RequestUpdateAsync(id);
            return await ViewEditorFormAsync(vm);
        }

        /// <summary>
        /// Attempts to update the existing relation.
        /// </summary>
        [HttpPost]
        [Route("update")]
        public async Task<ActionResult> Update(RelationEditorVM vm)
        {
            if(!ModelState.IsValid)
                return await ViewEditorFormAsync(vm);

            try
            {
                await _rels.UpdateAsync(vm, User);
                await _db.SaveChangesAsync();
                _alarm.FireTreeLayoutRegenerationRequired();

                return RedirectToSuccess("Связь обновлена");
            }
            catch(ValidationException ex)
            {
                SetModelState(ex);
                return await ViewEditorFormAsync(vm);
            }
        }

        /// <summary>
        /// Displays the relation removal confirmation.
        /// </summary>
        [HttpGet]
        [Route("remove")]
        public async Task<ActionResult> Remove(Guid id)
        {
            var vm = await _rels.RequestRemoveAsync(id);
            return View(vm);
        }

        /// <summary>
        /// Removes the relation.
        /// </summary>
        [HttpPost]
        [Route("remove")]
        public async Task<ActionResult> Remove(Guid id, bool confirm)
        {
            await _rels.RemoveAsync(id, User);
            await _db.SaveChangesAsync();
            _alarm.FireTreeLayoutRegenerationRequired();

            return RedirectToSuccess("Связь удалена");
        }

        /// <summary>
        /// Returns editor properties for the selected relation type.
        /// </summary>
        [HttpGet]
        [Route("editorProps")]
        public async Task<ActionResult> EditorProperties(RelationType relType)
        {
            return Json(_rels.GetPropertiesForRelationType(relType));
        }

        #region Helpers

        /// <summary>
        /// Displays the editor.
        /// </summary>
        private async Task<ActionResult> ViewEditorFormAsync(RelationEditorVM vm)
        {
            if(vm.SourceIds == null)
                vm.SourceIds = Array.Empty<Guid>();

            var pageIds = new[] {vm.DestinationId, vm.EventId}.Concat(vm.SourceIds.Cast<Guid?>()).ToList();
            var pageLookup = await _pages.FindPagesByIdsAsync(pageIds);

            ViewBag.Data = new RelationEditorDataVM
            {
                IsNew = vm.Id == Guid.Empty,
                SourceItems = GetPageLookup(vm.SourceIds),
                DestinationItem = GetPageLookup(vm.DestinationId ?? Guid.Empty),
                EventItem = GetPageLookup(vm.EventId ?? Guid.Empty),

                Properties = _rels.GetPropertiesForRelationType(vm.Type),
                RelationTypes = EnumHelper.GetEnumValues<RelationType>()
                                          .Select(x => new SelectListItem
                                          {
                                              Value = x.ToString(),
                                              Text = x.GetEnumDescription(),
                                              Selected = x == vm.Type
                                          })
            };

            return View("Editor", vm);

            IReadOnlyList<SelectListItem> GetPageLookup(params Guid[] ids)
            {
                var result = new List<SelectListItem>();

                foreach(var id in ids)
                    if(pageLookup.TryGetValue(id, out var page))
                        result.Add(new SelectListItem { Selected = true, Text = page.Title, Value = page.Id.ToString() });

                return result;
            }
        }

        /// <summary>
        /// Loads extra data for the filter.
        /// </summary>
        private async Task<RelationsListDataVM> GetDataAsync(RelationsListRequestVM request)
        {
            var data = new RelationsListDataVM();

            if (request.EntityId != null)
            {
                var title = await _db.Pages
                                     .Where(x => x.Id == request.EntityId)
                                     .Select(x => x.Title)
                                     .FirstOrDefaultAsync();

                if (title != null)
                    data.EntityTitle = title;
                else
                    request.EntityId = null;
            }

            return data;
        }

        #endregion
    }
}

src/Bonsai/Areas/Admin/Views/Relations/Editor.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Bonsai
@using Bonsai.Areas.Admin.ViewModels.Relations
@model RelationEditorVM
@{
    var data = (RelationEditorDataVM)ViewBag.Data;
    ViewBag.Title = data.IsNew ? "Создание связи" : "Редактор связи";
    Layout = "~/Areas/Admin/Views/Layout.cshtml";

    var formAction = Url.Action(data.IsNew ? "Create" : "Update", "Relations", new { area = "Admin" });

    string ShowIf(bool cond)
    {
        return cond ? "" : "display: none";
    }
}

<h1>@ViewBag.Title</h1>

<form action="@formAction" method="post" id="relation-editor-form">
    <input type="hidden" asp-for="Id" />

    <div class="form-row" data-tier="type">
        <div class="form-group col-md-8">
            <label class="form-label-required" asp-for="Type">Тип связи</label>
            <select asp-for="Type" asp-items="data.RelationTypes"></select>
            <span asp-validation-for="Type" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row" data-tier="destination">
        <div class="form-group col-md-8">
            <label class="form-label-required" asp-for="DestinationId">@data.Properties.DestinationName</label>
            <select asp-for="DestinationId" asp-items="data.DestinationItem"></select>
        </div>
    </div>

    <div class="form-row" data-tier="source">
        <div class="form-group col-md-8">
            <label class="form-label-required" asp-for="SourceIds">@data.Properties.SourceName</label>
            <select asp-for="SourceIds" asp-items="data.SourceItems" data-multiple="@data.IsNew.ToString()"></select>
            <div validation-list-for="DestinationId" validation-list-caption="Противоречивые факты" class="text-danger validation-result"></div>
        </div>
    </div>

    <div class="form-row" data-tier="duration" style="@ShowIf(data.Properties.ShowDuration)">
        <div class="form-group col-md-4">
            <label asp-for="DurationStart">Начало периода</label>
            <input type="text" class="form-control duration-start datepicker" asp-for="DurationStart" placeholder="ГГГГ.ММ.ДД" />
            <span asp-validation-for="DurationStart" class="text-danger"></span>
        </div>

        <div class="form-group col-md-4">
            <label asp-for="DurationEnd">Конец периода</label>
            <input type="text" class="form-control duration-end datepicker" asp-for="DurationEnd" placeholder="ГГГГ.ММ.ДД" />
            <span asp-validation-for="DurationEnd" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row" data-tier="event" style="@ShowIf(data.Properties.ShowEvent)">
        <div class="form-group col-md-8">
            <label asp-for="EventId">Ссылка на событие</label>
            <select asp-for="EventId" asp-items="data.EventItem"></select>
            <span asp-validation-for="EventId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-8">
            <button class="btn btn-primary" type="submit">Сохранить</button>
            <a class="btn btn-secondary" href="@Url.Action("Index", "Relations", new { area = "Admin" })">Назад</a>
        </div>
    </div>
</form>

src/Bonsai/Areas/Admin/Views/Relations/Index.cshtml
@using Bonsai.Areas.Admin.ViewModels.Relations
@using Bonsai.Code.DomainModel.Media
@using Impworks.Utils.Format
@addTagHelper *, Bonsai
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model RelationsListVM
@{
    ViewBag.Title = "Список связей";
    Layout = "~/Areas/Admin/Views/Layout.cshtml";

    var baseUrl = Url.Action("Index", "Relations", new { area = "Admin" });
}

<h1>Список связей</h1>

<div class="clearfix">
    <div class="float-left">
        <a class="btn btn-sm btn-outline-secondary" href="@Url.Action("Create", "Relations", new {area = "Admin"})" title="Создать новую связь">
            <span class="fa fa-plus-circle"></span>
            Создать
        </a>
    </div>
    <div class="float-right">
        <form action="@baseUrl" method="GET" class="form-inline">
            @await Component.InvokeAsync("ListHiddenFilterComponent", new
            {
                request = Model.Request,
                include = new [] { nameof(RelationsListRequestVM.EntityId) }
            })
            @if(Model.EntityTitle != null)
            {
                @await Component.InvokeAsync("ListItemFilterComponent", new
                {
                    url = baseUrl,
                    request = Model.Request,
                    propName = nameof(RelationsListRequestVM.EntityId),
                    title = Model.EntityTitle
                })
            }
            <input type="text" class="form-control form-control-sm mr-sm-2" name="@nameof(RelationsListRequestVM.SearchQuery)" value="@Model.Request.SearchQuery" placeholder="Имя страницы" />
            <button class="btn btn-sm btn-outline-secondary" type="submit">Найти</button>
        </form>
    </div>
</div>

@if(Model.Items.Any())
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th width="42%">@await Component.InvokeAsync("ListHeaderComponent", new { url = baseUrl, request = Model.Request, propName = nameof(RelationTitleVM.Destination), title = "Cтраница" })</th>
                <th width="16%">@await Component.InvokeAsync("ListHeaderComponent", new { url = baseUrl, request = Model.Request, propName = nameof(RelationTitleVM.Type), title = "Тип связи" })</th>
                <th width="42%">@await Component.InvokeAsync("ListHeaderComponent", new { url = baseUrl, request = Model.Request, propName = nameof(RelationTitleVM.Source), title = "Связанная страница" })</th>
                <th width="1px"></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var r in Model.Items)
            {
            <tr class="admin-row">
                <td class="hide-overflow">
                    <page-image image="@r.Destination.MainPhotoPath" type="@r.Destination.Type" size="@MediaSize.Small"></page-image>
                    <span title="@r.Destination.Title">@r.Destination.Title</span>
                </td>
                <td>
                    <a href="@Url.Action("Update", "Relations", new {area = "Admin", id = r.Id})" title="Редактировать">
                        @r.Type.GetEnumDescription()
                    </a>
                </td>
                <td class="hide-overflow">
                    <page-image image="@r.Source.MainPhotoPath" type="@r.Source.Type" size="@MediaSize.Small"></page-image>
                    <span title="@r.Source.Title">@r.Source.Title</span>
                </td>
                <td class="admin-row-actions">
                    <a href="@Url.Action("Remove", "Relations", new {area = "Admin", id = r.Id})">
                        <span class="fa fa-remove" title="Удалить"></span>
                    </a>
                    <a href="@Url.Action("Index", "Changesets", new {area = "Admin", entityId = r.Id})">
                        <span class="fa fa-database" title="История изменений"></span>
                    </a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}
else
{
    if(Model.Request.IsEmpty())
    {
        <div class="alert alert-info">
            Не добавлено ни одной связи. <br />
        </div>
    }
    else
    {
        <div class="alert alert-info">
            По запросу не найдено ни одной связи.
        </div>
    }
}

<div class="clearfix">
    <div class="pull-right">
        @await Component.InvokeAsync("ListPaginatorComponent", new
        {
            url = baseUrl,
            request = Model.Request,
            pageCount = Model.PageCount
        })
    </div>
</div>

src/Bonsai/Areas/Admin/Views/Relations/Remove.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Impworks.Utils.Format
@model Bonsai.Areas.Admin.ViewModels.Relations.RelationTitleVM
@{
    ViewBag.Title = "Удаление связи";
    Layout = "~/Areas/Admin/Views/Layout.cshtml";
}

<h1>Удаление связи</h1>

<p>
    Вы уверены, что хотите удалить страницу связь <b>@Model.Type.GetEnumDescription()</b>
    между страницами <b>@Model.Destination.Title</b> и <b>@Model.Source.Title</b>?<br />
    Отменить данную операцию будет невозможно.
</p>

<form action="@Url.Action("Remove", "Relations", new {area = "Admin"})" method="POST">
    <input type="hidden" name="confirm" value="true" />
    <input type="hidden" asp-for="Id" />
    <button class="btn btn-danger" type="submit">Удалить</button>
    <a href="@Url.Action("Index", "Relations", new {area = "Admin"})" class="btn btn-secondary">Отмена</a>
</form>