src/Bonsai/Areas/Front/ViewModels/Page/InfoBlock/FactGroupVM.cs
using System.Collections.Generic;
using Bonsai.Code.DomainModel.Facts;
using Bonsai.Code.DomainModel.Facts.Models;

namespace Bonsai.Areas.Front.ViewModels.Page.InfoBlock
{
    /// <summary>
    /// Group of related facts.
    /// </summary>
    public class FactGroupVM
    {
        /// <summary>
        /// Definition of the group.
        /// </summary>
        public FactDefinitionGroup Definition { get; set; }

        /// <summary>
        /// The set of fact data.
        /// </summary>
        public ICollection<FactModelBase> Facts { get; set; }
    }
}

src/Bonsai/Areas/Front/ViewModels/Page/InfoBlock/InfoBlockVM.cs
using System.Collections.Generic;
using Bonsai.Areas.Front.ViewModels.Media;

namespace Bonsai.Areas.Front.ViewModels.Page.InfoBlock
{
    /// <summary>
    /// The list of facts related to a particular page.
    /// </summary>
    public class InfoBlockVM
    {
        /// <summary>
        /// The photo (if specified).
        /// </summary>
        public MediaThumbnailVM Photo { get; set; }

        /// <summary>
        /// Facts about the person.
        /// </summary>
        public IReadOnlyCollection<FactGroupVM> Facts { get; set; }

        /// <summary>
        /// Groups of inferred relations.
        /// </summary>
        public IReadOnlyCollection<RelationCategoryVM> RelationGroups { get; set; }
    }
}

src/Bonsai/Areas/Front/ViewModels/Page/InfoBlock/RelatedPageVM.cs
using Bonsai.Code.Utils.Date;

namespace Bonsai.Areas.Front.ViewModels.Page.InfoBlock
{
    /// <summary>
    /// A single related page.
    /// </summary>
    public class RelatedPageVM: PageTitleVM
    {
        /// <summary>
        /// Range of the relation (if applicable).
        /// </summary>
        public FuzzyRange? Duration { get; set; }

        /// <summary>
        /// Page of the event bound to the relation.
        /// </summary>
        public PageTitleVM RelationEvent { get; set; }
    }
}

src/Bonsai/Areas/Front/ViewModels/Page/InfoBlock/RelationCategoryVM.cs
using System.Collections.Generic;

namespace Bonsai.Areas.Front.ViewModels.Page.InfoBlock
{
    /// <summary>
    /// Information about a list of relation groups.
    /// </summary>
    public class RelationCategoryVM
    {
        /// <summary>
        /// Title of the relations category.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Flag indicating that the category must be displayed at the top of the page.
        /// </summary>
        public bool IsMain { get; set; }

        /// <summary>
        /// List of nested groups.
        /// </summary>
        public IReadOnlyList<RelationGroupVM> Groups { get; set; }
    }
}

src/Bonsai/Areas/Front/ViewModels/Page/InfoBlock/RelationGroupVM.cs
using System.Collections.Generic;

namespace Bonsai.Areas.Front.ViewModels.Page.InfoBlock
{
    /// <summary>
    /// Information about a group of relations.
    /// </summary>
    public class RelationGroupVM
    {
        /// <summary>
        /// Relations in the group.
        /// </summary>
        public ICollection<RelationVM> Relations { get; set; }
    }
}

src/Bonsai/Areas/Front/ViewModels/Page/InfoBlock/RelationVM.cs
using System.Collections.Generic;

namespace Bonsai.Areas.Front.ViewModels.Page.InfoBlock
{
    /// <summary>
    /// Information about a particular relation.
    /// </summary>
    public class RelationVM
    {
        /// <summary>
        /// Readable title of the relation.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// List of related pages.
        /// </summary>
        public ICollection<RelatedPageVM> Pages { get; set; }
    }
}

src/Bonsai/Areas/Front/Controllers/PageController.cs
using System.Threading.Tasks;
using Bonsai.Areas.Front.Logic;
using Bonsai.Areas.Front.Logic.Auth;
using Bonsai.Areas.Front.ViewModels.Page;
using Bonsai.Code.Infrastructure;
using Bonsai.Code.Services;
using Bonsai.Code.Utils;
using Bonsai.Code.Utils.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bonsai.Areas.Front.Controllers
{
    /// <summary>
    /// The root controller for pages.
    /// </summary>
    [Area("Front")]
    [Route("p")]
    [Authorize(Policy = AuthRequirement.Name)]
    public class PageController: AppControllerBase
    {
        public PageController(PagePresenterService pages, TreePresenterService tree, AuthService auth, CacheService cache)
        {
            _pages = pages;
            _tree = tree;
            _auth = auth;
            _cache = cache;
        }

        private readonly PagePresenterService _pages;
        private readonly TreePresenterService _tree;
        private readonly AuthService _auth;
        private readonly CacheService _cache;

        /// <summary>
        /// Displays the page description.
        /// </summary>
        [Route("{key}")]
        public async Task<ActionResult> Description(string key)
        {
            var encKey = PageHelper.EncodeTitle(key);
            if (encKey != key)
                return RedirectToActionPermanent("Description", new {key = encKey});

            try
            {
                ViewBag.User = await _auth.GetCurrentUserAsync(User);
                var vm = new PageVM<PageDescriptionVM>
                {
                    Body = await _cache.GetOrAddAsync(key, async () => await _pages.GetPageDescriptionAsync(key)),
                    InfoBlock = await _cache.GetOrAddAsync(key, async () => await _pages.GetPageInfoBlockAsync(key))
                };

                return View(vm);
            }
            catch (RedirectRequiredException ex)
            {
                return RedirectToActionPermanent("Description", new {key = ex.Key});
            }
        }

        /// <summary>
        /// Displays the related media files.
        /// </summary>
        [Route("{key}/media")]
        public async Task<ActionResult> Media(string key)
        {
            var encKey = PageHelper.EncodeTitle(key);
            if (encKey != key)
                return RedirectToActionPermanent("Media", new { key = encKey });

            try
            {
                ViewBag.User = await _auth.GetCurrentUserAsync(User);
                var vm = new PageVM<PageMediaVM>
                {
                    Body = await _cache.GetOrAddAsync(key, async () => await _pages.GetPageMediaAsync(key)),
                    InfoBlock = await _cache.GetOrAddAsync(key, async () => await _pages.GetPageInfoBlockAsync(key))
                };
                return View(vm);
            }
            catch(RedirectRequiredException ex)
            {
                return RedirectToActionPermanent("Description", new { key = ex.Key });
            }
        }

        /// <summary>
        /// Displays the related media files.
        /// </summary>
        [Route("{key}/tree")]
        public async Task<ActionResult> Tree(string key)
        {
            var encKey = PageHelper.EncodeTitle(key);
            if (encKey != key)
                return RedirectToActionPermanent("Tree", new { key = encKey });

            try
            {
                ViewBag.User = await _auth.GetCurrentUserAsync(User);
                var vm = new PageVM<PageTreeVM>
                {
                    Body = await _cache.GetOrAddAsync(key, async () => await _pages.GetPageTreeAsync(key)),
                    InfoBlock = await _cache.GetOrAddAsync(key, async () => await _pages.GetPageInfoBlockAsync(key))
                };
                return View(vm);
            }
            catch(RedirectRequiredException ex)
            {
                return RedirectToActionPermanent("Tree", new { key = ex.Key });
            }
        }

        /// <summary>
        /// Returns the rendered tree.
        /// </summary>
        [Route("~/util/tree/{key}")]
        public async Task<ActionResult> GetTreeData(string key)
        {
            var encKey = PageHelper.EncodeTitle(key);
            var data = await _tree.GetTreeAsync(encKey);
            return Json(data);
        }
    }
}

src/Bonsai/Areas/Front/Views/Page/InfoBlock/FactGroupList.cshtml
@model IEnumerable<Bonsai.Areas.Front.ViewModels.Page.InfoBlock.FactGroupVM>

@foreach (var group in Model)
{
    <h6 class="fact-group-title">@group.Definition.Title</h6>
    <table class="fact-group">
        @foreach (var fact in group.Facts)
        {
            @await Html.PartialAsync("~/Areas/Front/Views/Page/Facts/" + fact.GetType().Name + ".cshtml", fact)
        }
    </table>
    <hr />
}

src/Bonsai/Areas/Front/Views/Page/InfoBlock/InfoBlock.cshtml
@using Bonsai.Areas.Front.ViewModels.Page
@using Bonsai.Areas.Front.ViewModels.Page.InfoBlock
@model InfoBlockVM
@{
    var pageVm = (PageTitleVM) ViewBag.PageModel.Body;
    var extras = new ViewDataDictionary(ViewData) { ["Facts"] = Model.Facts.SelectMany(x => x.Facts).ToList() };
}

<div class="page-info">
    @if(Model.Photo != null)
    {
        <div class="profile-photo">
            <img src="@Url.Content(Model.Photo.ThumbnailUrl)" alt="@pageVm.Title" />
        </div>
    }

    @await Html.PartialAsync("~/Areas/Front/Views/Page/InfoBlock/FactGroupList.cshtml", Model.Facts.Where(x => x.Definition.IsMain), extras)
    @await Html.PartialAsync("~/Areas/Front/Views/Page/InfoBlock/RelationCategoryList.cshtml", Model.RelationGroups.Where(x => x.IsMain), extras)

    @await Html.PartialAsync("~/Areas/Front/Views/Page/InfoBlock/FactGroupList.cshtml", Model.Facts.Where(x => x.Definition.IsMain == false), extras)
    @await Html.PartialAsync("~/Areas/Front/Views/Page/InfoBlock/RelationCategoryList.cshtml", Model.RelationGroups.Where(x => x.IsMain == false), extras)
</div>

src/Bonsai/Areas/Front/Views/Page/InfoBlock/RelationCategoryList.cshtml
@model IEnumerable<Bonsai.Areas.Front.ViewModels.Page.InfoBlock.RelationCategoryVM>

@foreach (var cat in Model)
{
    <h6>@cat.Title</h6>
    foreach (var group in cat.Groups)
    {
        <div class="relation-group">
            @foreach (var rel in group.Relations)
            {
                <div class="relation">
                    <div class="relation-title">@rel.Title</div>
                    <div class="relation-value">
                        <ul class="relations-list">
                            @foreach (var relPage in rel.Pages)
                            {
                                <li>
                                    <a href="@Url.Action("Description", "Page", new {key = relPage.Key, area = "Front"})">@relPage.Title</a>
                                    @if (relPage.Duration != null)
                                    {
                                        <span class="relation-range" title="@relPage.Duration.Value.ReadableRange">@relPage.Duration.Value.ShortReadableRange</span>
                                    }
                                    @if (relPage.RelationEvent != null)
                                    {
                                        <a href="@Url.Action("Description", "Page", new {key = relPage.RelationEvent.Key, area = "Front"})"
                                           class="relation-event-link" title="@relPage.RelationEvent.Title">
                                            <span class="fa fa-calendar-plus-o"></span>
                                        </a>
                                    }
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            }
        </div>
    }
    <hr />
}