src/Bonsai/Areas/Admin/Controllers/DashboardController.cs
using System.Threading.Tasks;
using Bonsai.Areas.Admin.Logic;
using Bonsai.Code.Utils.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace Bonsai.Areas.Admin.Controllers
{
    /// <summary>
    /// Controller for the default admin page.
    /// </summary>
    [Route("admin/home")]
    public class DashboardController: AdminControllerBase
    {
        public DashboardController(DashboardPresenterService dash)
        {
            _dash = dash;
        }

        private readonly DashboardPresenterService _dash;

        /// <summary>
        /// Displays the main page.
        /// </summary>
        [Route("")]
        public async Task<ActionResult> Index()
        {
            var vm = await _dash.GetDashboardAsync();
            return View(vm);
        }

        /// <summary>
        /// Returns the list of events at specified page.
        /// </summary>
        [Route("events")]
        public async Task<ActionResult> Events([FromQuery] int page = 0)
        {
            var vm = await _dash.GetEventsAsync(page).ToListAsync();
            return View(vm);
        }
    }
}

src/Bonsai/Areas/Admin/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bonsai.Areas.Admin.Logic;
using Bonsai.Areas.Admin.Logic.Workers;
using Bonsai.Areas.Admin.Utils;
using Bonsai.Areas.Admin.ViewModels.Media;
using Bonsai.Areas.Front.Logic;
using Bonsai.Code.DomainModel.Media;
using Bonsai.Code.Infrastructure.Attributes;
using Bonsai.Code.Utils.Helpers;
using Bonsai.Code.Utils.Validation;
using Bonsai.Data;
using Impworks.Utils.Strings;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;

namespace Bonsai.Areas.Admin.Controllers
{
    /// <summary>
    /// Controller for managing media files.
    /// </summary>
    [Route("admin/media")]
    public class MediaController: AdminControllerBase
    {
        public MediaController(MediaManagerService media, PagesManagerService pages, WorkerAlarmService workerAlarm, AppDbContext db)
        {
            _media = media;
            _pages = pages;
            _workerAlarm = workerAlarm;
            _db = db;
        }

        private readonly MediaManagerService _media;
        private readonly PagesManagerService _pages;
        private readonly WorkerAlarmService _workerAlarm;
        private readonly AppDbContext _db;

        /// <summary>
        /// Displays the list of pages.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Index(MediaListRequestVM request)
        {
            var vm = await _media.GetMediaAsync(request);
            return View(vm);
        }

        /// <summary>
        /// Displays the uploader form.
        /// </summary>
        [HttpGet]
        [Route("upload")]
        public async Task<ActionResult> Upload()
        {
            return View();
        }

        /// <summary>
        /// Handles a single file upload.
        /// </summary>
        [HttpPost]
        [Route("upload")]
        [ConfigurableRequestSizeLimit]
        public async Task<ActionResult> Upload(MediaUploadRequestVM vm, IFormFile file)
        {
            try
            {
                var result = await _media.UploadAsync(vm, file, User);
                result.ThumbnailPath = Url.Content(result.ThumbnailPath);

                await _db.SaveChangesAsync();

                if (!result.IsProcessed)
                    _workerAlarm.FireNewEncoderJob();

                return Json(result);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Error = true,
                    Description = ex.Message
                });
            }
        }

        /// <summary>
        /// Returns the thumbnail status for all specified media files.
        /// </summary>
        [HttpGet]
        [Route("thumbs")]
        public async Task<ActionResult> GetThumbnails(IEnumerable<Guid> ids)
        {
            var vms = await _media.GetThumbnailsAsync(ids);

            foreach(var vm in vms)
                vm.ThumbnailPath = Url.Content(vm.ThumbnailPath);

            return Json(vms);
        }

        /// <summary>
        /// Displays the update form for a media file.
        /// </summary>
        [HttpGet]
        [Route("update")]
        public async Task<ActionResult> Update(Guid id, MediaEditorSaveAction? saveAction = null)
        {
            var vm = await _media.RequestUpdateAsync(id);

            if (saveAction != null)
                vm.SaveAction = saveAction.Value;

            return await ViewEditorFormAsync(vm);
        }

        /// <summary>
        /// Updates the media data.
        /// </summary>
        [HttpPost]
        [Route("update")]
        public async Task<ActionResult> Update(MediaEditorVM vm)
        {
            if(!ModelState.IsValid)
                return await ViewEditorFormAsync(vm);

            try
            {
                await _media.UpdateAsync(vm, User);
                await _db.SaveChangesAsync();

                ShowMessage("Медиа-файл обновлен");

                if (vm.SaveAction == MediaEditorSaveAction.SaveAndShowNext)
                {
                    var nextId = await _media.GetNextUntaggedMediaAsync();
                    if (nextId != null)
                        return RedirectToAction("Update", new {id = nextId.Value, saveAction = vm.SaveAction});
                }

                return Redirect(DefaultActionUrl);
            }
            catch (ValidationException ex)
            {
                SetModelState(ex);
                return await ViewEditorFormAsync(vm);
            }
        }

        /// <summary>
        /// Removes the media file.
        /// </summary>
        [HttpGet]
        [Route("remove")]
        public async Task<ActionResult> Remove(Guid id)
        {
            ViewBag.Info = await _media.RequestRemoveAsync(id, User);
            return View(new RemoveMediaRequestVM { Id = id });
        }

        /// <summary>
        /// Removes the media file.
        /// </summary>
        [HttpPost]
        [Route("remove")]
        public async Task<ActionResult> Remove(RemoveMediaRequestVM vm)
        {
            await _media.RemoveAsync(vm, User);
            await _db.SaveChangesAsync();

            return RedirectToSuccess("Медиа-файл удален");
        }

        #region Helpers

        /// <summary>
        /// Displays the editor.
        /// </summary>
        private async Task<ActionResult> ViewEditorFormAsync(MediaEditorVM vm)
        {
            var depictedEntities = JsonConvert.DeserializeObject<MediaTagVM[]>(vm.DepictedEntities);
            var ids = depictedEntities.Select(x => x.PageId)
                                      .Concat(new[] {vm.Location, vm.Event}.Select(x => x.TryParse<Guid?>()))
                                      .ToList();

            var pageLookup = await _pages.FindPagesByIdsAsync(ids);

            foreach(var depicted in depictedEntities)
                if (depicted.PageId != null && pageLookup.TryGetValue(depicted.PageId.Value, out var depPage))
                    depicted.ObjectTitle = depPage.Title;

            ViewBag.Data = new MediaEditorDataVM
            {
                EventItem = GetPageLookup(vm.Event),
                LocationItem = GetPageLookup(vm.Location),
                DepictedEntityItems = GetDepictedEntitiesList(),
                SaveActions = ViewHelper.GetEnumSelectList(vm.SaveAction),
                ThumbnailUrl = MediaPresenterService.GetSizedMediaPath(vm.FilePath, MediaSize.Large)
            };

            return View("Editor", vm);

            SelectListItem[] GetPageLookup(string key)
            {
                if (key.TryParse<Guid?>() is Guid id)
                    return pageLookup.TryGetValue(id, out var page)
                        ? new[] {new SelectListItem {Selected = true, Text = page.Title, Value = page.Id.ToString()}}
                        : Array.Empty<SelectListItem>();

                return new[] {new SelectListItem {Selected = true, Text = key, Value = key}};
            }

            IReadOnlyList<SelectListItem> GetDepictedEntitiesList()
            {
                var result = new List<SelectListItem>();

                foreach (var entity in depictedEntities)
                {
                    var title = entity.PageId is Guid id && pageLookup.TryGetValue(id, out var page)
                        ? page.Title
                        : entity.ObjectTitle;

                    result.Add(new SelectListItem
                    {
                        Selected = true,
                        Text = title,
                        Value = entity.PageId?.ToString() ?? entity.ObjectTitle
                    });
                }

                return result;
            }
        }

        #endregion
    }
}

src/Bonsai/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bonsai.Areas.Admin.Logic;
using Bonsai.Areas.Admin.ViewModels.Users;
using Bonsai.Code.Services.Config;
using Bonsai.Code.Services.Search;
using Bonsai.Code.Utils;
using Bonsai.Code.Utils.Helpers;
using Bonsai.Code.Utils.Validation;
using Bonsai.Data;
using Bonsai.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Bonsai.Areas.Admin.Controllers
{
    /// <summary>
    /// Controller for managing users.
    /// </summary>
    [Route("admin/users")]
    public class UsersController : AdminControllerBase
    {
        public UsersController(UsersManagerService users, PagesManagerService pages, BonsaiConfigService config, ISearchEngine search, AppDbContext db)
        {
            _users = users;
            _pages = pages;
            _config = config;
            _search = search;
            _db = db;
        }

        private readonly UsersManagerService _users;
        private readonly PagesManagerService _pages;
        private readonly BonsaiConfigService _config;
        private readonly ISearchEngine _search;
        private readonly AppDbContext _db;

        /// <summary>
        /// Displays the list of users.
        /// </summary>
        [HttpGet]
        [Route("")]
        public async Task<ActionResult> Index([FromQuery] UsersListRequestVM vm)
        {
            var users = await _users.GetUsersAsync(vm);
            ViewBag.AllowPasswordAuth = _config.GetStaticConfig().Auth.AllowPasswordAuth;
            return View(users);
        }

        /// <summary>
        /// Displays the remove confirmation for a user.
        /// </summary>
        [HttpGet]
        [Route("remove")]
        public async Task<ActionResult> Remove(string id)
        {
            var vm = await _users.RequestRemoveAsync(id, User);
            return View(vm);
        }

        /// <summary>
        /// Displays the remove confirmation for a user.
        /// </summary>
        [HttpPost]
        [Route("remove")]
        public async Task<ActionResult> Remove(string id, bool confirm)
        {
            await _users.RemoveAsync(id, User);
            return RedirectToSuccess("Пользователь удален");
        }

        /// <summary>
        /// Displays the update form for a user.
        /// </summary>
        [HttpGet]
        [Route("update")]
        public async Task<ActionResult> Update(string id)
        {
            var vm = await _users.RequestUpdateAsync(id);
            return await ViewUpdateFormAsync(vm);
        }

        /// <summary>
        /// Updates the user.
        /// </summary>
        [HttpPost]
        [Route("update")]
        public async Task<ActionResult> Update(UserEditorVM vm)
        {
            if (!ModelState.IsValid)
                return await ViewUpdateFormAsync(vm);

            try
            {
                if (vm.CreatePersonalPage && await _users.CanCreatePersonalPageAsync(vm))
                {
                    var page = await _pages.CreateDefaultUserPageAsync(vm, User);
                    vm.PersonalPageId = page.Id;
                    vm.CreatePersonalPage = false;

                    await _search.AddPageAsync(page);
                }

                await _users.UpdateAsync(vm, User);

                await _db.SaveChangesAsync();

                return RedirectToSuccess("Пользователь обновлен");
            }
            catch (ValidationException ex)
            {
                SetModelState(ex);
                return await ViewUpdateFormAsync(vm);
            }
        }

        /// <summary>
        /// Displays the form for creating a new user.
        /// </summary>
        [HttpGet]
        [Route("create")]
        public async Task<ActionResult> Create()
        {
            CheckPasswordAuth();

            return await ViewCreateFormAsync(new UserCreatorVM { Role = UserRole.User });
        }

        /// <summary>
        /// Creates a new user.
        /// </summary>
        [HttpPost]
        [Route("create")]
        public async Task<ActionResult> Create(UserCreatorVM vm)
        {
            CheckPasswordAuth();

            if (!ModelState.IsValid)
                return await ViewCreateFormAsync(vm);

            try
            {
                if (vm.CreatePersonalPage)
                {
                    var page = await _pages.CreateDefaultUserPageAsync(vm, User);
                    vm.PersonalPageId = page.Id;
                    vm.CreatePersonalPage = false;
                    
                    await _search.AddPageAsync(page);
                }

                await _users.CreateAsync(vm);
                await _db.SaveChangesAsync();

                return RedirectToSuccess("Пользователь создан");
            }
            catch (ValidationException ex)
            {
                SetModelState(ex);
                return await ViewCreateFormAsync(vm);
            }
        }

        /// <summary>
        /// Displays the form for resetting a user password.
        /// </summary>
        [HttpGet]
        [Route("reset-password")]
        public async Task<ActionResult> ResetPassword(string id)
        {
            CheckPasswordAuth();

            return await ViewResetPasswordFormAsync(id);
        }

        /// <summary>
        /// Creates a new user.
        /// </summary>
        [HttpPost]
        [Route("reset-password")]
        public async Task<ActionResult> ResetPassword(UserPasswordEditorVM vm)
        {
            CheckPasswordAuth();

            try
            {
                await _users.ResetPasswordAsync(vm);
                return RedirectToSuccess("Пароль изменен");
            }
            catch (ValidationException ex)
            {
                SetModelState(ex);
                return await ViewResetPasswordFormAsync(vm.Id);
            }
        }

        #region Helpers

        /// <summary>
        /// Displays the form for creating a new password-authorized user.
        /// </summary>
        private async Task<ActionResult> ViewCreateFormAsync(UserCreatorVM vm)
        {
            var pageItems = await GetPageItemsAsync(vm.PersonalPageId);

            ViewBag.Data = new UserEditorDataVM
            {
                IsSelf = false,
                UserRoleItems = ViewHelper.GetEnumSelectList(vm.Role, except: new[] { UserRole.Unvalidated }),
                PageItems = pageItems
            };

            return View("Create", vm);
        }

        /// <summary>
        /// Displays the password reset form.
        /// </summary>
        private async Task<ActionResult> ViewResetPasswordFormAsync(string id)
        {
            ViewBag.Data = await _users.GetAsync(id);
            return View("ResetPassword", new UserPasswordEditorVM { Id = id });
        }

        /// <summary>
        /// Displays the UpdateUser form.
        /// </summary>
        private async Task<ActionResult> ViewUpdateFormAsync(UserEditorVM vm)
        {
            var canCreate = await _users.CanCreatePersonalPageAsync(vm);
            var pageItems = await GetPageItemsAsync(vm.PersonalPageId);

            ViewBag.Data = new UserEditorDataVM
            {
                IsSelf = _users.IsSelf(vm.Id, User),
                UserRoleItems = ViewHelper.GetEnumSelectList(vm.Role),
                CanCreatePersonalPage = canCreate,
                PageItems = pageItems
            };

            return View("Update", vm);
        }

        /// <summary>
        /// Returns the select list for a page picker.
        /// </summary>
        private async Task<IReadOnlyList<SelectListItem>> GetPageItemsAsync(Guid? pageId)
        {
            if (pageId != null)
            {
                var page = await _db.Pages
                                    .Where(x => x.Id == pageId)
                                    .Select(x => x.Title)
                                    .FirstOrDefaultAsync();

                if (!string.IsNullOrEmpty(page))
                    return new[] { new SelectListItem(page, pageId.Value.ToString(), true) };
            }

            return Array.Empty<SelectListItem>();
        }

        /// <summary>
        /// Checks if password authorization is enabled.
        /// </summary>
        private void CheckPasswordAuth()
        {
            if (!_config.GetStaticConfig().Auth.AllowPasswordAuth)
                throw new OperationException("Авторизация по паролю запрещена настройками.");
        }

        #endregion
    }
}

src/Bonsai/Areas/Admin/Views/Dashboard/Events.cshtml
@model IReadOnlyList<Bonsai.Areas.Admin.ViewModels.Dashboard.ChangesetEventVM>

@using System.Globalization
@using Bonsai.Areas.Admin.ViewModels.Changesets
@using Bonsai.Areas.Admin.ViewModels.Dashboard
@using Bonsai.Code.Utils.Helpers
@using Bonsai.Data.Models
@using Humanizer
@using Impworks.Utils.Strings

@{
    string GetChangeDescription(ChangesetEventVM evt)
    {
        var baseForm = evt.EntityType == ChangesetEntityType.Media
            ? evt.ChangeType switch {
                ChangesetType.Created => "загрузил",
                ChangesetType.Removed => "удалил",
                ChangesetType.Updated => "обновил",
                ChangesetType.Restored => "восстановил"
            }
            : evt.ChangeType switch {
                ChangesetType.Created => "создал",
                ChangesetType.Removed => "удалил",
                ChangesetType.Updated => "обновил",
                ChangesetType.Restored => "восстановил"
            };

        return evt.User.IsMale == false ? baseForm + "а" : baseForm;
    }

    string GetEntityName(ChangesetEntityType entity) => entity switch {
        ChangesetEntityType.Page => "cтраницу",
        ChangesetEntityType.Media => "медиа-файл",
        ChangesetEntityType.Relation => "связь"
    };

    string GetChangeClass(ChangesetType type) => type switch {
        ChangesetType.Created => "plus",
        ChangesetType.Removed => "times",
        ChangesetType.Updated => "pencil",
        ChangesetType.Restored => "undo"
    };

    string GetChangeDate(DateTimeOffset date)
    {
        return date < DateTimeOffset.Now.AddDays(-14)
            ? date.LocalDateTime.ToString("dd MMMM yyyy")
            : date.Humanize().Capitalize();
    }
}

@foreach (var evt in Model)
{

    <div class="row dashboard-event">
        <div class="col-auto p-0">
            <div class="dashboard-event-image-wrapper">
                <img src="@ViewHelper.GetGravatarUrl(evt.User.Email)" class="dashboard-event-image shadow-sm" title="@evt.User.FullName" />
                <div class="dashboard-event-icon">
                    <span class="fa fa-@(GetChangeClass(evt.ChangeType))"></span>
                </div>
            </div>
        </div>
        <div class="col p-0">
            <div class="row dashboard-event-header">
                <div class="col dashboard-event-title">
                    <h6>
                        @evt.User.FullName 
                        @if (evt.EntityType == ChangesetEntityType.Media)
                        {
                            <span>
                                @GetChangeDescription(evt)
                                @evt.ElementCount.DisplayNumeric("медиа-файл", "медиа-файла", "медиа-файлов")
                            </span>
                        }
                        else
                        {
                            <span>
                                @GetChangeDescription(evt)
                                @GetEntityName(evt.EntityType)
                            </span>
                        }
                    </h6>
                </div>
                <div class="col-auto dashboard-event-date" title="@evt.Date.LocalDateTime.ToString("dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture)">
                    @GetChangeDate(evt.Date)
                </div>
            </div>
            <div class="dashboard-event-content">
                @if (evt.MediaThumbnails?.Count > 0)
                {
                    <ul class="list-inline dashboard-event-media">
                        @foreach (var elem in evt.MediaThumbnails)
                        {
                            <li class="list-inline-item">
                                <div class="media-thumb-wrapper">
                                    @if (evt.ChangeType == ChangesetType.Removed)
                                    {
                                        <div class="media-thumb-square" style="background-image: url('@Url.Content(elem.ThumbnailUrl)')"></div>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("ViewMedia", "Media", new {area = "Front", key = elem.Key})" class="media-thumb-link" data-media="@elem.Key">
                                            <div class="media-thumb-square" style="background-image: url('@Url.Content(elem.ThumbnailUrl)')"></div>
                                        </a>
                                    }
                                </div>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    if (evt.MainLink != null)
                    {
                        @if (!string.IsNullOrEmpty(evt.MainLink.Url))
                        {
                            <a href="@evt.MainLink.Url">@evt.MainLink.Title</a>
                        }
                        else
                        {
                            <span>@evt.MainLink.Title</span>
                        }
                    }
                    @if (evt.EntityType == ChangesetEntityType.Relation && evt.ExtraLinks != null)
                    {
                        <span>
                            между страницами: <a href="@evt.ExtraLinks[0].Url">@evt.ExtraLinks[0].Title</a> и <a href="@evt.ExtraLinks[1].Url">@evt.ExtraLinks[1].Title</a>
                        </span>
                    }
                }
            </div>
        </div>
    </div>
}

src/Bonsai/Areas/Admin/Views/Dashboard/Index.cshtml
@using Bonsai.Code.Utils.Helpers
@model Bonsai.Areas.Admin.ViewModels.Dashboard.DashboardVM
@addTagHelper *, Bonsai
@{
    ViewBag.Title = "Панель администрации";
    Layout = "~/Areas/Admin/Views/Layout.cshtml";
}

<div class="dashboard-cards">
    <div class="card-deck">
        <div class="card">
            <a class="card-body" href="@Url.Action("Index", "Pages", new {area = "Admin"})">
                <h2 class="card-title text-center">@Model.PagesCount</h2>
                <p class="card-text text-center">@Model.PagesCount.DisplayNumeric("страница", "страницы", "страниц", false)</p>
            </a>
            @if (Model.PagesToImproveCount > 0)
            {
                <div class="card-footer">
                    <small class="text-muted">
                        <a href="@Url.Action("Index", "Pages", new {area = "Admin", OrderBy = "CompletenessScore", OrderDescending = false})">
                            @Model.PagesToImproveCount можно улучшить
                        </a>
                    </small>
                </div>
            }
        </div>

        <div class="card">
            <a class="card-body" href="@Url.Action("Index", "Media", new { area = "Admin" })">
                <h2 class="card-title text-center">@Model.MediaCount</h2>
                <p class="card-text text-center">@Model.MediaCount.DisplayNumeric("медиа-файл", "медиа-файла", "медиа-файлов", false)</p>
            </a>
            @if (Model.MediaToTagCount > 0)
            {
                <div class="card-footer">
                    <small class="text-muted">
                        <a href="@Url.Action("Index", "Media", new {area = "Admin"})">@Model.MediaToTagCount без отметок</a>
                    </small>
                </div>
            }
        </div>

        <div class="card">
            <a class="card-body" href="@Url.Action("Index", "Relations", new { area = "Admin" })">
                <h2 class="card-title text-center">@Model.RelationsCount</h2>
                <p class="card-text text-center">@Model.RelationsCount.DisplayNumeric("связь", "связи", "связей", false)</p>
            </a>
        </div>


        <div class="card">
            <a class="card-body" href="@Url.Action("Index", "Users", new { area = "Admin" })">
                <h2 class="card-title text-center">@Model.UsersCount</h2>
                <p class="card-text text-center">@Model.UsersCount.DisplayNumeric("пользователь", "пользователя", "пользователей", false)</p>
            </a>
            @if (Model.UsersPendingValidationCount > 0)
            {
                <div class="card-footer">
                    <small class="text-muted">
                        <a href="@Url.Action("Index", "Users", new {area = "Admin"})">@Model.UsersPendingValidationCount.DisplayNumeric("запрос", "запроса", "запросов") </a>
                    </small>
                </div>
            }
        </div>
    </div>
</div>

<div class="dashboard-events">
    @if (Model.Events?.Count > 0)
    {
        <div class="card">
            <div class="load-on-scroll" data-load-url="@Url.Action("Events", "Dashboard", new { area = "Admin" })" data-load-elem-class=".dashboard-event">
                @await Html.PartialAsync("Events", Model.Events)
            </div>
        </div>
    }
    else
    {
        <div class="alert alert-info">
            Здесь будет показываться список последних действий.<br />
            Вы можете создать <a href="@Url.Action("Index", "Pages", new { area = "Admin" } )">страницу</a> или <a href="@Url.Action("Upload", "Media", new { area = "Admin" })">загрузить медиа-файлы</a>.
        </div>
    }
</div>